/** Friendly aliases for the generated API schema types. */
import type { components } from './schema'

type Schemas = components['schemas']

export type Health = Schemas['Health']
export type LibraryInfo = Schemas['LibraryInfo']
export type LibraryFolder = Schemas['LibraryFolder']
export type ImportRequest = Schemas['ImportRequest']
export type DirListing = Schemas['DirListing']
export type DirEntry = Schemas['DirEntry']
export type Photo = Schemas['Photo']
export type PhotoDetail = Schemas['PhotoDetail']
export type PhotoEdit = Schemas['PhotoEdit']
export type PhotoPage = Schemas['Page_Photo_']
export type PhotoSort = Schemas['PhotoSort']
export type SortOrder = Schemas['SortOrder']
export type AdjustmentParams = Schemas['AdjustmentParams']
export type StyleSummary = Schemas['StyleSummary']
export type Style = Schemas['StyleView']
export type StyleSample = Schemas['StyleSample']
export type ExportPreset = Schemas['ExportPreset']
export type ExportSettings = Schemas['ExportSettings-Output']
export type ExportSettingsInput = Schemas['ExportSettings-Input']
export type Job = Schemas['Job']
export type JobItem = Schemas['JobItem']
export type JobKind = Schemas['JobKind']
export type JobStatus = Schemas['JobStatus']
export type ApplyStyleRequest = Schemas['ApplyStyleRequest']
export type ExportRequest = Schemas['ExportRequest']
export type ApplyAndExportRequest = Schemas['ApplyAndExportRequest']
export type JobRequest = ApplyStyleRequest | ExportRequest | ApplyAndExportRequest

export type FileFormat = Schemas['FileFormat']
export type ColorSpace = Schemas['ColorSpace']
export type ResizeMode = Schemas['ResizeMode']
export type Orientation = Schemas['Orientation']
export type CropAnchor = Schemas['CropAnchor']
export type SharpenFor = Schemas['SharpenFor']
export type SharpenAmount = Schemas['SharpenAmount']
export type MetadataPolicy = Schemas['MetadataPolicy']
export type CollisionPolicy = Schemas['CollisionPolicy']
export type TiffCompression = Schemas['TiffCompression']
export type ExportTarget = Schemas['ExportTarget']
